_commit: v1.6.12-8-g50e0997
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: node-feature-discovery
helmRelease: node-feature-discovery
helmRepo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
helmValues: helm/values.yaml
helmVersion: ''
ingress: false
labels: 'app.kubernetes.io/name: node-feature-discovery'
name: node-feature-discovery
namespace: node-feature-discovery
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://kubernetes-sigs.github.io/node-feature-discovery/stable/get-started/index.html
url: https://github.com/charlesthomas/homelab-node-feature-discovery
