---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-node-feature-discovery
commonLabels:
  app.kubernetes.io/name: node-feature-discovery

resources:
- resources/namespaces.yaml
helmCharts:
- name: node-feature-discovery
  namespace: node-feature-discovery
  releaseName: node-feature-discovery
  repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  valuesFile: helm/values.yaml
