---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-node-feature-discovery
commonLabels:
  app.kubernetes.io/name: node-feature-discovery

resources:
- resources/namespaces.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: node-feature-discovery
      namespace: node-feature-discovery
      annotations:
        gethomepage.dev/href: https://node-feature-discovery.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: node-feature-discovery
        gethomepage.dev/name: node-feature-discovery
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
helmCharts:
- name: node-feature-discovery
  namespace: node-feature-discovery
  releaseName: node-feature-discovery
  repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  valuesFile: helm/values.yaml
