---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-node-feature-discovery
commonLabels:
  app.kubernetes.io/name: node-feature-discovery

resources:
- resources/configmaps.yaml
- resources/crds.yaml
- resources/daemonsets.yaml
- resources/deployments.yaml
- resources/jobs.yaml
- resources/namespaces.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
