---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-master-conf
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
data:
  nfd-master.conf: "null"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-topology-updater-conf
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
data:
  nfd-topology-updater.conf: "null"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-feature-discovery-worker-conf
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
data:
  nfd-worker.conf: |-
    sources:
      usb:
        deviceClassWhiteList:
        - "02"
        - 0e
        - ef
        - fe
        - ff
