---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-feature-discovery-prune
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
    verbs:
      - get
      - patch
      - update
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-feature-discovery-topology-updater
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - topology.node.k8s.io
    resources:
      - noderesourcetopologies
    verbs:
      - create
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-feature-discovery-worker
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-feature-discovery-worker
subjects:
  - kind: ServiceAccount
    name: nfd-worker
    namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-feature-discovery
subjects:
  - kind: ServiceAccount
    name: nfd-master
    namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-feature-discovery-gc
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-feature-discovery-gc
subjects:
  - kind: ServiceAccount
    name: nfd-gc
    namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-feature-discovery-prune
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-feature-discovery-prune
subjects:
  - kind: ServiceAccount
    name: node-feature-discovery-prune
    namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-feature-discovery-topology-updater
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-feature-discovery-topology-updater
subjects:
  - kind: ServiceAccount
    name: nfd-topology-updater
    namespace: node-feature-discovery
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-feature-discovery-worker
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
rules:
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeatures
    verbs:
      - create
      - get
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
    verbs:
      - get
      - patch
      - update
      - list
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeatures
      - nodefeaturerules
      - nodefeaturegroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeaturegroups/status
    verbs:
      - patch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resourceNames:
      - nfd-master.nfd.kubernetes.io
    resources:
      - leases
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-feature-discovery-gc
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
  - apiGroups:
      - topology.node.k8s.io
    resources:
      - noderesourcetopologies
    verbs:
      - delete
      - list
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeatures
    verbs:
      - delete
      - list
