---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfd-gc
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfd-master
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfd-topology-updater
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfd-worker
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-feature-discovery-prune
  namespace: node-feature-discovery
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/name: node-feature-discovery
